# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.delete_all
Book.delete_all

# User Seeds
demo_user = User.create(username: 'demo', email: 'demo@demo.com', password: 'demolicious')

# Book Seeds

mexican_gothic = Book.create(title: 'Mexican Gothic', author: 'Silvia Moreno-Garcia', page_count: 301, published_date: 'June 30, 2020', description: 'After receiving a frantic letter from her newly-wed cousin begging for someone to save her from a mysterious doom, Noemí Taboada heads to High Place, a distant house in the Mexican countryside. She’s not sure what she will find—her cousin’s husband, a handsome Englishman, is a stranger, and Noemí knows little about the region. Noemí is also an unlikely rescuer: She’s a glamorous debutante, and her chic gowns and perfect red lipstick are more suited for cocktail parties than amateur sleuthing. But she’s also tough and smart, with an indomitable will, and she is not afraid: Not of her cousin’s new husband, who is both menacing and alluring; not of his father, the ancient patriarch who seems to be fascinated by Noemí; and not even of the house itself, which begins to invade Noemí’s dreams with visions of blood and doom. Her only ally in this inhospitable abode is the family’s youngest son. Shy and gentle, he seems to want to help Noemí, but might also be hiding dark knowledge of his family’s past. For there are many secrets behind the walls of High Place. The family’s once colossal wealth and faded mining empire kept them from prying eyes, but as Noemí digs deeper she unearths stories of violence and madness. And Noemí, mesmerized by the terrifying yet seductive world of High Place, may soon find it impossible to ever leave this enigmatic house behind.', cover_img_url: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1607462569l/53152636._SY475_.jpg')
ninteen_eighty_four = Book.create(title: '1984', author: 'George Orwell', page_count: 298, published_date: 'April 8, 1949', description: 'Among the seminal texts of the 20th century, Nineteen Eighty-Four is a rare work that grows more haunting as its futuristic purgatory becomes more real. Published in 1949, the book offers political satirist George Orwell\'s nightmarish vision of a totalitarian, bureaucratic world and one poor stiff\'s attempt to find individuality. The brilliance of the novel is Orwell\'s prescience of modern life—the ubiquity of television, the distortion of the language—and his ability to construct such a thorough version of hell. Required reading for students since it was published, it ranks among the most terrifying novels ever written.', cover_img_url: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1532714506l/40961427._SX318_.jpg')
six_of_crows = Book.create(title: 'Six of Crows', author: 'Leigh Bardugo', page_count: 465, published_date: 'September 29, 2015', description: 'Ketterdam: a bustling hub of international trade where anything can be had for the right price—and no one knows that better than criminal prodigy Kaz Brekker. Kaz is offered a chance at a deadly heist that could make him rich beyond his wildest dreams. But he can’t pull it off alone. Kaz’s crew is the only thing that might stand between the world and destruction—if they don’t kill each other first.', cover_img_url: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1628438817l/23437156._SX318_.jpg')
rise_of_kyoshi = Book.create(title: 'Rise of Kyoshi', author: 'F.C. Yee', page_count: 442, published_date: 'July 16, 2019', description: 'F. C. Yee’s The Rise of Kyoshi delves into the story of Kyoshi, the Earth Kingdom–born Avatar. The longest-living Avatar in this beloved world’s history, Kyoshi established the brave and respected Kyoshi Warriors, but also founded the secretive Dai Li, which led to the corruption, decline, and fall of her own nation. The first of two novels based on Kyoshi, The Rise of Kyoshi maps her journey from a girl of humble origins to the merciless pursuer of justice who is still feared and admired centuries after she became the Avatar.', cover_img_url: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1535687326l/41104164.jpg')
attack_on_titan = Book.create(title: 'Attack on Titan Vol. 1', author: 'Hajime Isayama', page_count: 193, published_date: 'July 19, 2012', description: 'For the past century, what\'s left of mankind has hidden in a giant, three-walled city, trapped in fear of the bizarre, giant humanoids known as the Titans. Little is known about where they came from or why they are bent on consuming humankind, but the sudden appearance of an enormous Titan is about to change everything...', cover_img_url: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1432712438l/13154150._SX318_.jpg')
words_of_radiance = Book.create(title: 'Words of Radiance', author: 'Brandon Sanderson', page_count: 1087, published_date: 'March 4, 2014', description: 'Expected by his enemies to die the miserable death of a military slave, Kaladin survived to be given command of the royal bodyguards, a controversial first for a low-status "darkeyes." Now he must protect the king and Dalinar from every common peril as well as the distinctly uncommon threat of the Assassin, all while secretly struggling to master remarkable new powers that are somehow linked to his honorspren, Syl. The Assassin, Szeth, is active again, murdering rulers all over the world of Roshar, using his baffling powers to thwart every bodyguard and elude all pursuers. Among his prime targets is Highprince Dalinar, widely considered the power behind the Alethi throne. His leading role in the war would seem reason enough, but the Assassin\'s master has much deeper motives. Brilliant but troubled Shallan strives along a parallel path. Despite being broken in ways she refuses to acknowledge, she bears a terrible burden: to somehow prevent the return of the legendary Voidbringers and the civilization-ending Desolation that will follow. The secrets she needs can be found at the Shattered Plains, but just arriving there proves more difficult than she could have imagined. Meanwhile, at the heart of the Shattered Plains, the Parshendi are making an epochal decision. Hard pressed by years of Alethi attacks, their numbers ever shrinking, they are convinced by their war leader, Eshonai, to risk everything on a desperate gamble with the very supernatural forces they once fled. The possible consequences for Parshendi and humans alike, indeed, for Roshar itself, are as dangerous as they are incalculable.', cover_img_url: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1507307927l/17332218.jpg')
sharp_objects = Book.create(title: 'Sharp Objects', author: 'Gillian Flynn', page_count: 254, published_date: 'September 26, 2006', description: 'Fresh from a brief stay at a psych hospital, reporter Camille Preaker faces a troubling assignment: she must return to her tiny hometown to cover the unsolved murder of a preteen girl and the disappearance of another. For years, Camille has hardly spoken to her neurotic, hypochondriac mother or to the half-sister she barely knows: a beautiful thirteen-year-old with an eerie grip on the town. Now, installed in her old bedroom in her family\'s Victorian mansion, Camille finds herself identifying with the young victims—a bit too strongly. Dogged by her own demons, she must unravel the psychological puzzle of her own past if she wants to get the story—and survive this homecoming.', cover_img_url: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1475695315l/18045891.jpg')
recursion = Book.create(title: 'Recursion', author: 'Blake Crouch', page_count: 326, published_date: 'June 11, 2019', description: 'Memory makes reality. That\'s what NYC cop Barry Sutton is learning, as he investigates the devastating phenomenon the media has dubbed False Memory Syndrome—a mysterious affliction that drives its victims mad with memories of a life they never lived. That\'s what neuroscientist Helena Smith believes. It\'s why she\'s dedicated her life to creating a technology that will let us preserve our most precious memories. If she succeeds, anyone will be able to re-experience a first kiss, the birth of a child, the final moment with a dying parent. As Barry searches for the truth, he comes face to face with an opponent more terrifying than any disease—a force that attacks not just our minds, but the very fabric of the past. And as its effects begin to unmake the world as we know it, only he and Helena, working together, will stand a chance at defeating it. But how can they make a stand when reality itself is shifting and crumbling all around them? At once a relentless pageturner and an intricate science-fiction puzzlebox about time, identity, and memory, Recursion is a thriller as only Blake Crouch could imagine it—and his most ambitious, mind-boggling, irresistible work to date.', cover_img_url: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1543687940l/42046112.jpg')
earnest = Book.create(title: 'The Importance of Being Earnest', author: 'Oscar Wilde', page_count: 104, published_date: 'February 14, 1895', description: 'This final play from the pen of Oscar Wilde is a stylish send-up of Victorian courtship and manners, complete with assumed names, mistaken lovers, and a lost handbag. Jack and Algernon are best friends, both wooing ladies who think their names are Ernest, "that name which inspires absolute confidence." Wilde\'s effervescent wit, scathing social satire, and high farce make this one of the most cherished plays in the English language.', cover_img_url: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1365270881l/11060744.jpg')
tkam = Book.create(title: 'To Kill A Mockingbird', author: 'Harper Lee', page_count: 324, published_date: 'July 11, 1960', description: 'The unforgettable novel of a childhood in a sleepy Southern town and the crisis of conscience that rocked it. "To Kill A Mockingbird" became both an instant bestseller and a critical success when it was first published in 1960. It went on to win the Pulitzer Prize in 1961 and was later made into an Academy Award-winning film, also a classic. Compassionate, dramatic, and deeply moving, "To Kill A Mockingbird" takes readers to the roots of human behavior - to innocence and experience, kindness and cruelty, love and hatred, humor and pathos. Now with over 18 million copies in print and translated into forty languages, this regional story by a young Alabama woman claims universal appeal. Harper Lee always considered her book to be a simple love story. Today it is regarded as a masterpiece of American literature.', cover_img_url: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1553383690l/2657.jpg')
mockingjay = Book.create(title: 'Mockingjay', author: 'Suzanne Collins', page_count: 398, published_date: 'August 24, 2010', description: 'Katniss Everdeen, girl on fire, has survived, even though her home has been destroyed. Gale has escaped. Katniss\'s family is safe. Peeta has been captured by the Capitol. District 13 really does exist. There are rebels. There are new leaders. A revolution is unfolding. It is by design that Katniss was rescued from the arena in the cruel and haunting Quarter Quell, and it is by design that she has long been part of the revolution without knowing it. District 13 has come out of the shadows and is plotting to overthrow the Capitol. Everyone, it seems, has had a hand in the carefully laid plans—except Katniss. The success of the rebellion hinges on Katniss\'s willingness to be a pawn, to accept responsibility for countless lives, and to change the course of the future of Panem. To do this, she must put aside her feelings of anger and distrust. She must become the rebels\' Mockingjay—no matter what the personal cost.', cover_img_url: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1586722918l/7260188._SY475_.jpg')
bleach = Book.create(title: 'Bleach―ブリーチ― 74', author: 'Tite Kubo', page_count: 232, published_date: 'November 4, 2016', description: 'ずっと護り続けたい絆があるから、男は戦う――。仲間と刻んできた想いの全てを刀に込め、一護はユーハバッハとの最終決戦へ！　死神vs滅却師、千年に亘る永き因縁の結末は…！　感動の『BLEACH』最終巻', cover_img_url: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1477669456l/30843523._SY475_.jpg')
kindred = Book.create(title: 'Kindred', author: 'Octavia E. Butler', page_count: 287, published_date: 'June 1, 1979', description: 'The first science fiction written by a black woman, Kindred has become a cornerstone of black American literature. This combination of slave memoir, fantasy, and historical fiction is a novel of rich literary complexity. Having just celebrated her 26th birthday in 1976 California, Dana, an African-American woman, is suddenly and inexplicably wrenched through time into antebellum Maryland. After saving a drowning white boy there, she finds herself staring into the barrel of a shotgun and is transported back to the present just in time to save her life. During numerous such time-defying episodes with the same young man, she realizes the challenge she’s been given...', cover_img_url: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1339423248l/60931.jpg')
never_let_me_go = Book.create(title: 'Never Let Me Go', author: 'Kazuo Ishiguro', page_count: 288, published_date: 'August 31, 2010', description: 'Hailsham seems like a pleasant English boarding school, far from the influences of the city. Its students are well tended and supported, trained in art and literature, and become just the sort of people the world wants them to be. But, curiously, they are taught nothing of the outside world and are allowed little contact with it. Within the grounds of Hailsham, Kathy grows from schoolgirl to young woman, but it’s only when she and her friends Ruth and Tommy leave the safe grounds of the school (as they always knew they would) that they realize the full truth of what Hailsham is.', cover_img_url: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1353048590l/6334.jpg')
norse_mythology = Book.create(title: 'Norse Mythology', author: 'Neil Gaiman', page_count: 301, published_date: 'March 6, 2018', description: 'Neil Gaiman, long inspired by ancient mythology in creating the fantastical realms of his fiction, presents a bravura rendition of the Norse gods and their world from their origin though their upheaval in Ragnarok. In Norse Mythology, Gaiman stays true to the myths in envisioning the major Norse pantheon: Odin, the highest of the high, wise, daring, and cunning; Thor, Odin’s son, incredibly strong yet not the wisest of gods; and Loki—son of a giant—blood brother to Odin and a trickster and unsurpassable manipulator. Gaiman fashions these primeval stories into a novelistic arc that begins with the genesis of the legendary nine worlds and delves into the exploits of deities, dwarfs, and giants. Through Gaiman’s deft and witty prose, these gods emerge with their fiercely competitive natures, their susceptibility to being duped and to duping others, and their tendency to let passion ignite their actions, making these long-ago myths breathe pungent life again.', cover_img_url: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1516128292l/37903770._SX318_.jpg')
prince_and_discourses = Book.create(title: 'The Prince and the Discourses', author: 'Niccolò Machiavelli', page_count: 592, published_date: 'January 1, 1531', description: 'This volume includes the complete translated texts of both The Prince and the Discourses on the First Ten Books of Titus Livius [Livy], along with a historical and critical Introduction by Max Lerner.', cover_img_url: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1387747931l/780639.jpg')

# Bookshelf Seeds

# Review Seeds

# Comment Seeds